version: "3.4"

x-common: &common
  image: app:local
  labels:
    com.app: app
  networks:
    - app
  volumes:
    - build:/app/build/

services:
  builder:
    volumes:
      - build:/app/build/
      - .:/app:delegated
    <<: *common
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      cache_from:
        - "app:local"
        - "app:${BRANCH_NAME:-ignore}"
    container_name: web-app-builder
    working_dir: /app
    command:
      [
        sh,
        -c,
        "rm -rf ./build/* && ./node_modules/.bin/tsc -w --pretty --skipLibCheck --outDir build/src",
      ]

  js:
    image: app:local
    env_file:
      - .env.dist
    depends_on:
      - postgres
    networks:
      - app

  web_api:
    <<: *common
    working_dir: /app/build
    container_name: web_api
    command:
      [
        sh,
        -c,
        "node --watch --inspect=0.0.0.0 -r source-map-support/register ./src/index.js",
      ]
    hostname: web_api
    depends_on:
      - postgres
    ports:
      - 2000:2000
      - 4000:4000
      - 9229:9229
    networks:
      - app

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: app
    networks:
      - app

networks:
  app:

volumes:
  build:
